export const structures: Structures = [
  [["spike", [0, 0]]],
  [
    ["spike", [0, 0]],
    ["spike", [4, 0]],
    ["spike", [5, 0]],
  ],
  [
    ["spike", [0, 0]],
    ["slab", [4, 0]],
  ],
  [
    ["slab", [0, 0]],
    ["spike", [1, 0]],
    ["spike", [2, 0]],
    ["spike", [3, 0]],
  ],
  [
    ["slab", [0, 0]],
    ["slab", [1, 0]],
    ["slab", [2, 0]],
    ["slab", [3, 0]],
    ["spike", [3, -1]],
    ["spike", [8, 0]],
  ],
  [
    ["spike", [0, 0]],
    ["slab", [1, 0]],
    ["slab", [2, 0]],
    ["slab", [3, 0]],
    ["slab", [4, 0]],
    ["spike", [4, -1]],
  ],
  [
    ["spike", [0, 0]],
    ["slab", [1, 0]],
    ["spike", [2, 0]],
    ["spike", [3, 0]],
    ["spike", [4, 0]],
  ],
  [
    ["spike", [0, 0]],
    ["slab", [1, 0]],
    ["slab", [3, 0]],
    ["spike", [3, -1]],
  ],
  [
    ["slab", [0, -1]],
    ["slab", [1, -1]],
    ["slab", [2, -1]],
    ["spike", [5, 0]],
  ],
  [
    ["spike", [0, 0]],
    ["slab", [1, 0]],
    ["slab", [3, -1]],
    ["slab", [4, -1]],
    ["slab", [5, -1]],
    ["spike", [7, 0]],
    ["spike", [8, 0]],
  ],
];
